// LOGIN DATA TYPE
export const LOGIN_USER_DATA = "LOGIN_USER_DATA";
export const LOGIN_USER_TOKEN_DATA = "LOGIN_USER_TOKEN_DATA";
// PASTUE DATA TYPE
export const PASTURE_NAME_DATA = "PASTURE_NAME_DATA";
export const PASTURE_DATA = "PASTURE_DATA";
// error
export const PASTURE_NAME_NO = "PASTURE_NAME_NO";
export const PASTURE_NAMEMEAN_NO = "PASTURE_NAMEMEAN_NO";
// HORSE DATA TYPE
export const HORSE_ALL_DATA = "HORSE_ALL_DATA";
export const HORSE_CHECK_DATA = "HORSE_CHECK_DATA";
export const HORSE_CHECK_AGE = "HORSE_CHECK_AGE";
export const HORSE_SAVE_DATA = "HORSE_SAVE_DATA";
export const SHOW_HORSE_GROW = "SHOW_HORSE_GROW";
// HORSE NAME VALIDATION TYPE
export const HORSE_NAME_VALIDATION = "HORSE_NAME_VALIDATION";
export const HORSE_NAME_ILLEGAL = "HORSE_NAME_ILLEGAL";

// INSTITUION DATA TYPE
export const POOL_BUY_DATA = "POOL_BUY_DATA";
export const PASTURE_BUY_DATA = "PASTURE_BUY_DATA";
export const ROAD_BUY_DATA = "ROAD_BUY_DATA";
export const TRUCK_BUY_DATA = "TRUCK_BUY_DATA";
export const LONGIFIELD_BUY_DATA = "LONGIFIELD_BUY_DATA";
// GET RACEPLAN
export const GET_THIS_WEEK_RACE_PLAN = "GET_THIS_WEEK_RACE_PLAN";
export const GET_LAST_WEEK_RACE_PLAN = "GET_LAST_WEEK_RACE_PLAN";
export const GET_BEFOR_WEEK_RACE_PLAN = "GET_BEFOR_WEEK_RACE_PLAN";
export const GET_NEXT_WEEK_RACE_PLAN = "GET_NEXT_WEEK_RACE_PLAN";
export const GET_NEXT_NEXT_WEEK_RACE_PLAN = "GET_NEXT_NEXT_WEEK_RACE_PLAN";
export const GET_NEXT_NEXT_NEXT_WEEK_RACE_PLAN =
  "GET_NEXT_NEXT_NEXT_WEEK_RACE_PLAN";
// HORSE STATE ARROW_POSITION_STATE
export const ARROW_POSITION_STATE = "ARROW_POSITION_STATE";
export const ODDS_RANDOM_DATA = "ODDS_RANDOM_DATA";
export const NUMBER_RANDOM_DATA = "NUMBER_RANDOM_DATA";
export const RACING_RANDOM_HORSE_DATA = "RACING_RANDOM_HORSE_DATA";
// SET GAME TIME SHOW
export const GAME_TIME = "GAME_TIME";
export const GAME_F_COUNT_DOWN = "GAME_F_COUNT_DOWN";
export const GAME_S_COUNT_DOWN = "GAME_S_COUNT_DOWN";
export const GAME_T_COUNT_DOWN = "GAME_T_COUNT_DOWN";
export const RESERVATION_DATA = "RESERVATION_DATA";
// STABLE DATA
export const GET_STABLE_MENU = "GET_STABLE_MENU";
export const STABLE_MENU_DATA = "STABLE_MENU_DATA";

// JocKey Register.
export const MALE_REGISTER = "MALE_REGISTER";
export const FEMALE_REGISTER = "FEMALE_REGISTER";
export const GENDER_REGISTER = "GENDER_REGISTER";
export const JOCKEY_NAME_REGISTER = "JOCKEY_NAME_REGISTER";
export const ALL_REGISTER = "ALL_REGISTER";
export const SHOW_JOCKEY = "SHOW_JOCKEY";
// Institution Type
export const INSTITUTION_MENU_DATA = "INSTITUTION_MENU_DATA";
export const POOL_LEVELUP_DATA = "POOL_LEVELUP_DATA";
export const STALL_LEVELUP_DATA = "STALL_LEVELUP_DATA";
export const ROAD_LEVELUP_DATA = "ROAD_LEVELUP_DATA";
export const TRUCK_LEVELUP_DATA = "TRUCK_LEVELUP_DATA";
export const LONGIFIELD_LEVELUP_DATA = "LONGIFIELD_LEVELUP_DATA";
// REVER
export const PREESET_PASTURE_DATA = "PREESET_PASTURE_DATA";
export const PREESET_PASTURE_NAMES = "PREESET_PASTURE_NAMES";
export const PREESET_STALL_DATA = "PREESET_STALL_DATA";
export const PREESET_STALL_NAMES = "PREESET_STALL_NAMES";
// RACE REGISTER
export const GET_RACE_CORSE_DATA = "GET_RACE_CORSE_DATA";
export const GET_RACE_PRIZE_DATA = "GET_RACE_PRIZE_DATA";
export const GET_RACE_JOCKEYS_DATA = "GET_RACE_JOCKEYS_DATA";
export const GET_RACE_REGISTER_DATA = "GET_RACE_REGISTER_DATA";
export const GET_RACE_WEEK = "GET_RACE_WEEK";
export const GET_RACE_CPU_HOURSE = "GET_RACE_CPU_HOURSE";
// RACING TYPE
export const RACE_RESULT_DATA = "RACE_RESULT_DATA";
export const RACING_HORSE_DATA = "RACING_HORSE_DATA";
export const RACING_JOCKEY_DATA = "RACING_JOCKEY_DATA";
export const LAST_RACE_RESULT_DATA = "LAST_RACE_RESULT_DATA";

// DIMENSION ACTION
export const DIMENSIONS_SIZE = "DIMENSIONS_SIZE";
export const DIMENSIONS_SIZE_WIDTH = "DIMENSIONS_SIZE_WIDTH";
export const DIMENSIONS_SIZE_HEIGHT = "DIMENSIONS_SIZE_HEIGHT";

// REGISTERING TYPE
export const REGISTERING_DATA = "REGISTERING_DATA";

// MARRYBUTTON TYPE 
export const MARRY_BUTTON_ACTION = "MARRY_BUTTON_ACTION";