// LOGIN DATA TYPE
export const LOGIN_USER_DATA = 'LOGIN_USER_DATA';
export const LOGIN_UESR_PASTURE_DATA = 'LOGIN_UESR_PASTURE_DATA';
export const LOGIN_USER_TOKEN_DATA = 'LOGIN_USER_TOKEN_DATA';
// PASTUE DATA TYPE
export const PASTURE_NAME_DATA = 'PASTURE_NAME_DATA';
export const PASTURE_SIZE_DATA = 'PASTURE_SIZE_DATA';
// error
export const PASTURE_NAME_NO = 'PASTURE_NAME_NO';
export const PASTURE_NAMEMEAN_NO = 'PASTURE_NAMEMEAN_NO';
export const UPBRINGING_DATA = 'UPBRINGING_DATA';
// HORSE DATA TYPE
export const HORSE_ALL_DATA = 'HORSE_ALL_DATA';
export const HORSE_SELECT_DATA = 'HORSE_SELECT_DATA';
export const HORSE_CHECK_DATA = 'HORSE_CHECK_DATA';
export const HORSE_AMOUNT_DATA = 'HORSE_AMOUNT_DATA';
export const HORSE_BLOOD_DATA = 'HORSE_BLOOD_DATA';
export const HORSE_NAME_DATA = 'HORSE_NAME_DATA';
export const HORSE_CHECK_ALL_DATA = 'HORSE_CHECK_ALL_DATA';
// INSTITUION DATA TYPE
export const POOL_BUY_DATA = 'POOL_BUY_DATA';
export const PASTURE_BUY_DATA = 'PASTURE_BUY_DATA';
export const ROAD_BUY_DATA = 'ROAD_BUY_DATA';
export const TRUCK_BUY_DATA = 'TRUCK_BUY_DATA';
export const LONGIFIELD_BUY_DATA = 'LONGIFIELD_BUY_DATA';