// LOGIN DATA TYPE
export const LOGIN_USER_DATA = 'LOGIN_USER_DATA';
// PASTUE DATA TYPE
export const PASTURE_NAME_DATA = 'PASTURE_NAME_DATA';
export const PASTURE_SIZE_DATA = 'PASTURE_SIZE_DATA';
// error
export const PASTURE_NAME_NO = 'PASTURE_NAME_NO';
export const PASTURE_NAMEMEAN_NO = 'PASTURE_NAMEMEAN_NO';
// HORSE DATA TYPE
export const HORSE_ALL_DATA = 'HORSE_ALL_DATA';
export const HORSE_SELECT_DATA = 'HORSE_SELECT_DATA';
export const HORSE_CHECK_DATA = 'HORSE_CHECK_DATA';
export const HORSE_AMOUNT_DATA = 'HORSE_AMOUNT_DATA';
export const HORSE_BLOOD_DATA = 'HORSE_BLOOD_DATA';
export const HORSE_NAME_DATA = 'HORSE_NAME_DATA';