//---------------------------------------
// inbreeding start
//---------------------------------------
export const INBREEDING_SPEED = [
  { left: +10, right: "10%" },
  { left: +9, right: "10%" },
  { left: +8, right: "10%" },
  { left: +7, right: "10%" },
  { left: +6, right: "10%" },
  { left: +5, right: "10%" },
  { left: +4, right: "10%" },
  { left: +3, right: "10%" },
  { left: +2, right: "10%" },
  { left: +1, right: "10%" },
  { left: 0, right: "0%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const INBREEDING_STAMINA = [
  { left: +10, right: "10%" },
  { left: +9, right: "10%" },
  { left: +8, right: "10%" },
  { left: +7, right: "10%" },
  { left: +6, right: "10%" },
  { left: +5, right: "10%" },
  { left: +4, right: "10%" },
  { left: +3, right: "10%" },
  { left: +2, right: "10%" },
  { left: +1, right: "10%" },
  { left: 0, right: "0%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const INBREEDING_CONDITION = [
  { left: +10, right: "0%" },
  { left: +9, right: "0%" },
  { left: +8, right: "0%" },
  { left: +7, right: "0%" },
  { left: +6, right: "0%" },
  { left: +5, right: "0%" },
  { left: +4, right: "0%" },
  { left: +3, right: "0%" },
  { left: +2, right: "0%" },
  { left: +1, right: "0%" },
  { left: 0, right: "2%" },
  { left: -1, right: "2%" },
  { left: -2, right: "2%" },
  { left: -3, right: "2%" },
  { left: -4, right: "2%" },
  { left: -5, right: "2%" },
  { left: -6, right: "10%" },
  { left: -7, right: "20%" },
  { left: -8, right: "20%" },
  { left: -9, right: "20%" },
  { left: -10, right: "20%" },
];

export const INBREEDING_HEALTH = [
  { left: +10, right: "0%" },
  { left: +9, right: "0%" },
  { left: +8, right: "0%" },
  { left: +7, right: "0%" },
  { left: +6, right: "0%" },
  { left: +5, right: "0%" },
  { left: +4, right: "0%" },
  { left: +3, right: "0%" },
  { left: +2, right: "0%" },
  { left: +1, right: "0%" },
  { left: 0, right: "2%" },
  { left: -1, right: "2%" },
  { left: -2, right: "2%" },
  { left: -3, right: "2%" },
  { left: -4, right: "2%" },
  { left: -5, right: "2%" },
  { left: -6, right: "10%" },
  { left: -7, right: "20%" },
  { left: -8, right: "20%" },
  { left: -9, right: "20%" },
  { left: -10, right: "20%" },
];

//---------------------------------------
// inbreeding end
//---------------------------------------
//---------------------------------------
// miracle start
//---------------------------------------
export const MIRACLE_SPEED = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const MIRACLE_STRENGTH = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const MIRACLE_MOMENT = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const MIRACLE_STAMINA = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const MIRACLE_CONDITION = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const MIRACLE_HEALTH = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];
//---------------------------------------
// miracle end
//---------------------------------------
//---------------------------------------
// know start
//---------------------------------------
export const KNOW_MOMENT = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const KNOW_STRENGTH = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "4%" },
  { left: +3, right: "4%" },
  { left: +2, right: "4%" },
  { left: +1, right: "4%" },
  { left: 0, right: "4%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];
//---------------------------------------
// know end
//---------------------------------------
//---------------------------------------
// match start
//---------------------------------------
export const MATCH_STAMINA = [
  { left: +10, right: "15%" },
  { left: +9, right: "15%" },
  { left: +8, right: "15%" },
  { left: +7, right: "15%" },
  { left: +6, right: "15%" },
  { left: +5, right: "5%" },
  { left: +4, right: "5%" },
  { left: +3, right: "5%" },
  { left: +2, right: "5%" },
  { left: +1, right: "5%" },
  { left: 0, right: "0%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];
//---------------------------------------
// match end
//---------------------------------------
//---------------------------------------
// good friend start
//---------------------------------------
export const GOOD_FRIEND_SPEED = [
  { left: +10, right: "10%" },
  { left: +9, right: "10%" },
  { left: +8, right: "10%" },
  { left: +7, right: "10%" },
  { left: +6, right: "10%" },
  { left: +5, right: "10%" },
  { left: +4, right: "10%" },
  { left: +3, right: "10%" },
  { left: +2, right: "10%" },
  { left: +1, right: "10%" },
  { left: 0, right: "0%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];

export const GOOD_FRIEND_STRENGTH = [
  { left: +10, right: "10%" },
  { left: +9, right: "10%" },
  { left: +8, right: "10%" },
  { left: +7, right: "10%" },
  { left: +6, right: "10%" },
  { left: +5, right: "10%" },
  { left: +4, right: "10%" },
  { left: +3, right: "10%" },
  { left: +2, right: "10%" },
  { left: +1, right: "10%" },
  { left: 0, right: "0%" },
  { left: -1, right: "0%" },
  { left: -2, right: "0%" },
  { left: -3, right: "0%" },
  { left: -4, right: "0%" },
  { left: -5, right: "0%" },
  { left: -6, right: "0%" },
  { left: -7, right: "0%" },
  { left: -8, right: "0%" },
  { left: -9, right: "0%" },
  { left: -10, right: "0%" },
];
//---------------------------------------
// good friend end
//---------------------------------------
//---------------------------------------
// final start
//---------------------------------------
export const FINAL_SPEED = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "15%" },
    { left: +5, right: "15%" },
    { left: +4, right: "15%" },
    { left: +3, right: "15%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
  
  export const FINAL_STRENGTH = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "15%" },
    { left: +5, right: "15%" },
    { left: +4, right: "15%" },
    { left: +3, right: "15%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
  
  export const FINAL_MOMENT = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "15%" },
    { left: +5, right: "15%" },
    { left: +4, right: "15%" },
    { left: +3, right: "15%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
  
  export const FINAL_STAMINA = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "15%" },
    { left: +5, right: "15%" },
    { left: +4, right: "15%" },
    { left: +3, right: "15%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
  
  export const FINAL_CONDITION = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "15%" },
    { left: +5, right: "15%" },
    { left: +4, right: "15%" },
    { left: +3, right: "15%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
  
  export const FINAL_HEALTH = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "15%" },
    { left: +5, right: "15%" },
    { left: +4, right: "15%" },
    { left: +3, right: "15%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
//--------------------------------------
// final end
//--------------------------------------
//--------------------------------------
// triple crown start
//--------------------------------------
export const TRIPLE_CROWN_SPEED = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "10%" },
    { left: +5, right: "10%" },
    { left: +4, right: "10%" },
    { left: +3, right: "10%" },
    { left: +2, right: "10%" },
    { left: +1, right: "10%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
  
  export const TRIPLE_CROWN_STRENGTH = [
    { left: +10, right: "10%" },
    { left: +9, right: "10%" },
    { left: +8, right: "10%" },
    { left: +7, right: "10%" },
    { left: +6, right: "10%" },
    { left: +5, right: "10%" },
    { left: +4, right: "10%" },
    { left: +3, right: "10%" },
    { left: +2, right: "10%" },
    { left: +1, right: "10%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
//--------------------------------------
// triple crown end
//--------------------------------------
//--------------------------------------
// shot reversal start
//--------------------------------------
export const SHOT_REVERSAL_SPEED = [
    { left: +10, right: "30%" },
    { left: +9, right: "0%" },
    { left: +8, right: "0%" },
    { left: +7, right: "0%" },
    { left: +6, right: "0%" },
    { left: +5, right: "0%" },
    { left: +4, right: "0%" },
    { left: +3, right: "0%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "70%" },
  ];
  
  export const SHOT_REVERSAL_STRENGTH = [
    { left: +10, right: "30%" },
    { left: +9, right: "0%" },
    { left: +8, right: "0%" },
    { left: +7, right: "0%" },
    { left: +6, right: "0%" },
    { left: +5, right: "0%" },
    { left: +4, right: "0%" },
    { left: +3, right: "0%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "70%" },
  ];
  
  export const SHOT_REVERSAL_MOMENT = [
    { left: +10, right: "30%" },
    { left: +9, right: "0%" },
    { left: +8, right: "0%" },
    { left: +7, right: "0%" },
    { left: +6, right: "0%" },
    { left: +5, right: "0%" },
    { left: +4, right: "0%" },
    { left: +3, right: "0%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "70%" },
  ];
  
  export const SHOT_REVERSAL_STAMINA = [
    { left: +10, right: "30%" },
    { left: +9, right: "0%" },
    { left: +8, right: "0%" },
    { left: +7, right: "0%" },
    { left: +6, right: "0%" },
    { left: +5, right: "0%" },
    { left: +4, right: "0%" },
    { left: +3, right: "0%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "70%" },
  ];
  
  export const SHOT_REVERSAL_CONDITION = [
    { left: +10, right: "30%" },
    { left: +9, right: "0%" },
    { left: +8, right: "0%" },
    { left: +7, right: "0%" },
    { left: +6, right: "0%" },
    { left: +5, right: "0%" },
    { left: +4, right: "0%" },
    { left: +3, right: "0%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "70%" },
  ];
  
  export const SHOT_REVERSAL_HEALTH = [
    { left: +10, right: "30%" },
    { left: +9, right: "0%" },
    { left: +8, right: "0%" },
    { left: +7, right: "0%" },
    { left: +6, right: "0%" },
    { left: +5, right: "0%" },
    { left: +4, right: "0%" },
    { left: +3, right: "0%" },
    { left: +2, right: "0%" },
    { left: +1, right: "0%" },
    { left: 0, right: "0%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "70%" },
  ];
//--------------------------------------
// shot reversal end
//--------------------------------------
//--------------------------------------
// outbild start
//--------------------------------------
export const OUTBLID_STAMINA = [
    { left: +10, right: "2%" },
    { left: +9, right: "2%" },
    { left: +8, right: "2%" },
    { left: +7, right: "2%" },
    { left: +6, right: "2%" },
    { left: +5, right: "2%" },
    { left: +4, right: "2%" },
    { left: +3, right: "22%" },
    { left: +2, right: "22%" },
    { left: +1, right: "22%" },
    { left: 0, right: "20%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];

export const OUTBLID_HEALTH = [
    { left: +10, right: "2%" },
    { left: +9, right: "2%" },
    { left: +8, right: "2%" },
    { left: +7, right: "2%" },
    { left: +6, right: "2%" },
    { left: +5, right: "2%" },
    { left: +4, right: "2%" },
    { left: +3, right: "22%" },
    { left: +2, right: "22%" },
    { left: +1, right: "22%" },
    { left: 0, right: "20%" },
    { left: -1, right: "0%" },
    { left: -2, right: "0%" },
    { left: -3, right: "0%" },
    { left: -4, right: "0%" },
    { left: -5, right: "0%" },
    { left: -6, right: "0%" },
    { left: -7, right: "0%" },
    { left: -8, right: "0%" },
    { left: -9, right: "0%" },
    { left: -10, right: "0%" },
  ];
//--------------------------------------
// outbild end
//--------------------------------------